import type { Metadata } from "next";
import { Geist } from 'next/font/google'
import "./globals.css";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { ConvexClientProvider } from "@/components/convex-client-provider";

const geist = Geist({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={geist.className}>
        <body
          className={`antialiased`}
          >
          <NuqsAdapter>
            <ConvexClientProvider>
              {children}
            </ConvexClientProvider>
          </NuqsAdapter>
        </body>
      </html>
  );
}
